# Generated by Django 5.2.8 on 2025-11-26 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('especie', models.CharField(max_length=120, unique=True)),
                ('raza', models.CharField(max_length=120, unique=True)),
                ('color', models.CharField(max_length=120, unique=True)),
                ('fecha_nacimiento', models.DateTimeField()),
                ('peso_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nombre_duenio', models.CharField(max_length=120, unique=True)),
                ('telefono_duenio', models.CharField(max_length=15, unique=True)),
                ('email_duenio', models.CharField(max_length=120, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('nombre',),
            },
        ),
    ]
