# Generated by Django 5.2.8 on 2025-11-26 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
