# Generated by Django 5.2.8 on 2025-11-26 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0002_alter_mascota_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='color',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='email_duenio',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='especie',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='nombre',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='nombre_duenio',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='raza',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='telefono_duenio',
            field=models.CharField(max_length=15),
        ),
    ]
