# Generated by Django 5.2.8 on 2025-11-27 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0003_alter_mascota_color_alter_mascota_email_duenio_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mascota',
            options={'ordering': ('isbn',)},
        ),
        migrations.RenameField(
            model_name='mascota',
            old_name='fecha_nacimiento',
            new_name='anio_publicacion',
        ),
        migrations.RenameField(
            model_name='mascota',
            old_name='color',
            new_name='autor',
        ),
        migrations.RenameField(
            model_name='mascota',
            old_name='email_duenio',
            new_name='copias_disponibles',
        ),
        migrations.RenameField(
            model_name='mascota',
            old_name='especie',
            new_name='editorial',
        ),
        migrations.RenameField(
            model_name='mascota',
            old_name='nombre',
            new_name='estado',
        ),
        migrations.RenameField(
            model_name='mascota',
            old_name='nombre_duenio',
            new_name='isbn',
        ),
        migrations.RenameField(
            model_name='mascota',
            old_name='raza',
            new_name='titulo',
        ),
        migrations.RenameField(
            model_name='mascota',
            old_name='telefono_duenio',
            new_name='ubicacion',
        ),
        migrations.RemoveField(
            model_name='mascota',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='mascota',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='mascota',
            name='peso_kg',
        ),
        migrations.RemoveField(
            model_name='mascota',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='mascota',
            name='categoria',
            field=models.CharField(default='sin_categoria', max_length=20),
        ),
        migrations.AddField(
            model_name='mascota',
            name='num_paginas',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
